#default DRQN config

model_config:
  model: None
  name: "_cart_pole"
  input_shape: None
  action_space: None
  lstm_size: 64
  discount_factor : 0.9
  n_step: 1
  batch_size: 32
  double_network: False
  priority: False
  tau: 1.0
  
optimizer_config:
  optimizer_name: "adam"
  optimizer_params:
    learning_rate: 0.01
    epsilon: 0.001
    clipnorm: 1.0
  custom_optimizer: None

buffer_config:
  size: 10000
  priority: False
  recurrent: True
  trace_length: 15
  recurrent_skip: 5
  n_step: None
  discount_factor : None
  eps: None
  alpha: None
  beta: None
  beta_changing: None
  beta_changing_curve: None
  max_priority: None

exploration_config:
  strategy_name: "epsilon_greedy"
  strategy_config:
    eps_decay_steps: 5000
    eps_max: 1.0
    eps_min: 0.01
    eps_test: 0.001
    action_space: None

data_saver:
  path: "..\\rl_lib\\examples\\drqn\\cart_pole/"
  copy_path: ""
    
