#default DQN config

model_config:
  model: None
  name: ""
  input_shape: None
  action_space: None
  discount_factor : 0.99
  
optimizer_config:
  optimizer_name: "adam"
  optimizer_params:
    learning_rate: 1e-4
    epsilon: 1e-3
    clipnorm: 1.0
  cutom_optimizer: None

buffer_config:
  size: 100000
  priority: False
  n_step: 1
  discount_factor : None
  eps: None
  alpha: None
  beta: None
  beta_changing: None
  beta_changing_curve: None
  max_priority: None

exploration_config:
  strategy_name: "epsilon_greedy"
  strategy_config:
    eps_decay_steps: 100000
    eps_max: 1.0
    eps_min: 0.1
    eps_test: 0.001
    action_spase: None

data_saver:
  path: ""
  copy_path: ""
    
